name: Vulnerability Scan
on:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Clone SBOM Alert Generator
        run: |
          git clone https://github.com/mifugnius/SBOMAlertGenerator.git
  
      - name: Install dependencies
        run: |
          cd SBOMAlertGenerator
          pip install -r requirements.txt
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Run vulnerability scan on PR branch
        run: |
          echo "Running Alert Generator on branch ${{ github.event.pull_request.head.ref }}"
          python SBOMAlertGenerator/main.py --directory-to-scan=. --no-email
